apiVersion: v1
kind: Service
metadata:
  name: namenode-service
spec:
  type: LoadBalancer
  ports:
    - name: "9870"
      port: 9870
      protocol: TCP
      targetPort: 9870
    - name: "8020"
      port: 8020
      protocol: TCP
      targetPort: 8020
  selector:
    app: namenode
