apiVersion: v1
kind: Service
metadata:
  name: namenode-service
spec:
  type: LoadBalancer
  ports:
    - name: "9870"
      port: 9870
      protocol: TCP
      targetPort: 9870
    - name: "9000"
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: namenode